// 全局状态类
export const APP_HEADER = 'APP_HEADER'
export const APP_LOADING = 'APP_LOADING'
export const APP_PLAYBAR = 'APP_PLAYBAR'
export const PART_LOADING = 'PART_LOADING'

export const LISTEN_LIST_STATUS = 'LISTEN_LIST_STATUS'


// 音乐列表
export const ADD_LISTEN_LISTS = 'ADD_LISTEN_LISTS'
export const ADD_ALL_TO_LISTEN_LISTS = 'ADD_ALL_TO_LISTEN_LISTS'
export const REMOVE_LISTEN_LISTS = 'REMOVE_LISTEN_LISTS'
export const REMOVE_ALL_LISTEN_LISTS = 'REMOVE_ALL_LISTEN_LISTS'
export const GET_POPULAR_LISTS = 'GET_POPULAR_LISTS'
export const GET_CLASSICAL_LISTS = 'GET_CLASSICAL_LISTS'
export const GET_LIGHT_LISTS = 'GET_LIGHT_LISTS'
export const GET_RADIO_LISTS = 'GET_RADIO_LISTS'

// 音乐操作
export const SET_AUDIO = 'SET_AUDIO'
export const SET_AUDIO_URL = 'SET_AUDIO_URL'
export const SET_PRE_AUDIO = 'SET_PRE_AUDIO'
export const SET_NEXT_AUDIO = 'SET_NEXT_AUDIO'
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING'
export const GET_MUSIC_LYRIC = 'GET_MUSIC_LYRIC'
export const SET_MUSIC_TIME = 'SET_MUSIC_TIME'